name: Blank Issue
description: Create a blank issue. ONLY USE THIS IF THE BUG CANNOT BE REPRODUCED IN VANILLA VENCORD!

body:
    - type: textarea
      id: content
      attributes:
          label: Content
      validations:
          required: true

    - type: checkboxes
      id: agreement-check
      attributes:
          label: Request Agreement
          options:
              - label: I have read the requirements for opening an issue above
                required: true
